us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
}
    
# invert the dictionary
abbrev_to_us_state = dict(map(reversed, us_state_to_abbrev.items()))

fema_action_to_disaster = {
    'Acquisition/Demolition': 'Hydrological',
    'Acquisition of Vacant Land': 'Hydrological',
    'Acquisition/Relocation': 'Hydrological',
    # 'Other (Specify in Comments)': 'Geophysical',   #! IMPORTANT, if you're reading this: this is a dummy variable and must be changed
    'Mitigation Reconstruction': 'Geophysical',     #! IMPORTANT, if you're reading this: this is a dummy variable and must be changed
    # 'Retro (1/15/2008 - DSG)': 'Geophysical',       #! IMPORTANT, if you're reading this: this is a dummy variable and must be changed
    'Elevation': 'Hydrological',
    'Floodproofed': 'Hydrological',
    'Safe Room/Wind Shelter': 'Meteorological',
    'Seismic Retrofit': 'Geophysical',
    'Wildfire Retrofit': 'Geophysical',
    'Wind Retrofit': 'Meteorological',
    'Wind Retrofit Advanced(A-P804)': 'Meteorological',
    'Wind Retrofit Basic (B-P804)': 'Meteorological',
    'Wind Retrofit Estimated(ES-P804)': 'Meteorological',
}